### PR TITLE
updated readme

### PR DESCRIPTION
**Pull request by sbdchd**

### CODE REVIEW

**Comment by munyari** [comment]
Hey @rhysd :smile: Is there anything holding this PR from being merged? The README could do with some updating in its language

**Comment by justinmk** [comment]
the wording changes in this PR are obfuscated by the numerous whitespace changes.

**Comment by munyari** [comment]
Cool, I might submit another PR

**Comment by rhysd** [comment]
I'm not a native speaker.  So, I'm not sure that the changes in this PR are valid or not without any description.  Please help me by describing why the change was added.  Line comments in the diff is most helpful.  For example, you changed `=====` title to `#` section header at line 1, but they are essentially the same and I didn't know why the change was added.

**Comment by sbdchd** [comment]
I think by making significant formatting changes, along with grammar / spelling, this pull request is unreadable & not very useful.

For that reason, I think it is better to close.

**Comment by rhysd** [comment]
@sbdchd Thank you.  It must be helpful :smile:

**Comment by munyari** [comment]
I just opened another PR, #73

**Pull request closed without merging**
